// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvef3KfcFWQi6a0Y3KDJ0vho_sxBi9Ou4',
    appId: '1:662514684473:web:3e5f133407b6c25379b3e8',
    messagingSenderId: '662514684473',
    projectId: 'bundadini-e5f11',
    authDomain: 'bundadini-e5f11.firebaseapp.com',
    storageBucket: 'bundadini-e5f11.firebasestorage.app',
    measurementId: 'G-82PYERTVP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD1FX92zYg7rASOcCjH_aMCDTgUy9iAfc',
    appId: '1:662514684473:android:b598ab91bffed03c79b3e8',
    messagingSenderId: '662514684473',
    projectId: 'bundadini-e5f11',
    storageBucket: 'bundadini-e5f11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9v4yDaAQw3Xpe3IGtGh-TryjvYkioPxU',
    appId: '1:662514684473:ios:661bad75851b605a79b3e8',
    messagingSenderId: '662514684473',
    projectId: 'bundadini-e5f11',
    storageBucket: 'bundadini-e5f11.firebasestorage.app',
    iosBundleId: 'com.example.bundadini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9v4yDaAQw3Xpe3IGtGh-TryjvYkioPxU',
    appId: '1:662514684473:ios:661bad75851b605a79b3e8',
    messagingSenderId: '662514684473',
    projectId: 'bundadini-e5f11',
    storageBucket: 'bundadini-e5f11.firebasestorage.app',
    iosBundleId: 'com.example.bundadini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvef3KfcFWQi6a0Y3KDJ0vho_sxBi9Ou4',
    appId: '1:662514684473:web:33b7da3b100a5be479b3e8',
    messagingSenderId: '662514684473',
    projectId: 'bundadini-e5f11',
    authDomain: 'bundadini-e5f11.firebaseapp.com',
    storageBucket: 'bundadini-e5f11.firebasestorage.app',
    measurementId: 'G-430W69DBXZ',
  );
}
